### ISSUE TITLE
Request of models

### ISSUE THREAD

**Issue by ozvi** [raman325/pyviziosoundbar#1]
Hi!

Great library!
I tried to use the project on my Vizio sb but it didn't work :(

Can you state the model your project works on?

Thanks,
Oz.

**Comment by raman325** [comment]
@ozvi These changes have been ported back to the original [pyvizio](https://github.com/vkorn/pyvizio) project. Can you open the issue there where it will have more visibility?

**Comment by raman325** [comment]
to answer your question btw, I have an SB4031-D5

**Comment by ozvi** [comment]
Thanks @raman325
